; Script generated by Antigravity for TinyRec
; Professional Inno Setup Script

#define AppName "Tiny Screen Recorder"
#define AppVersion "2.0.0"
#define AppPublisher "Shaki"
#define AppURL "https://github.com/meetshaks/Tiny-Screen-recorder"
#define AppExeName "TinyRec.exe"
#define AppId "{{B7C1D2A3-E4F5-46B7-8C9D-0E1F2A3B4C5D}"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
AppId={#AppId}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}
AppUpdatesURL={#AppURL}
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
AllowNoIcons=yes
; Require admin privileges to ensure audio driver installation works correctly
PrivilegesRequired=admin
OutputDir=.
OutputBaseFilename=Tiny_Recorder_V2_Setup
SetupIconFile=icon\icon.ico
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
UninstallDisplayIcon={app}\{#AppExeName}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\{#AppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; We don't need to include icon or dependency folders separately because 
; they are already bundled into the TinyRec.exe by PyInstaller (onefile).

[Icons]
; Main Start Menu shortcut (Always created for easy pinning)
Name: "{autoprograms}\{#AppName}"; Filename: "{app}\{#AppExeName}"
; Group folder shortcut (Optional but good for organization)
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExeName}"
Name: "{group}\{cm:UninstallProgram,{#AppName}}"; Filename: "{uninstallexe}"
; Desktop shortcut (User optional)
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#AppExeName}"; Description: "{cm:LaunchProgram,{#AppName}}"; Flags: nowait postinstall skipifsilent
